[tool.poetry]
name = "ctseg"
version = "0.1.0"
description = ""
authors = ["gnefihs <sfsy1@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
